title: "Evaluating Phylogenetic Tree Construction methods : Distance-based and Character-based"
description: <tagline> CAP5510 - Pushparaj Britto - 9178-5569</tagline>
google_analytics: 
show_downloads: true
theme: jekyll-theme-slate

gems:
  - jekyll-mentions
